<?php
if(!is_admin() && !can('can_manage_menu')){echo '<div class="card">Menu permission denied.</div>';return;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$a=$_POST['action']??'';
 if($a==='cat'){db()->prepare("INSERT INTO categories(name,sort_order) VALUES(?,?)")->execute([trim($_POST['name']), (int)$_POST['sort_order']]);flash('Category added.');}
 if($a==='item'){db()->prepare("INSERT INTO menu_items(category_id,name,description,price,sort_order,available) VALUES(?,?,?,?,?,?)")->execute([(int)$_POST['category_id'],trim($_POST['name']),trim($_POST['description']),max(0,(float)$_POST['price']),(int)$_POST['sort_order'],isset($_POST['available'])?1:0]);flash('Menu item added.');}
 if($a==='toggle'){db()->prepare("UPDATE menu_items SET available=1-available WHERE id=?")->execute([(int)$_POST['id']]);flash('Item availability updated.');}
 if($a==='price'){db()->prepare("UPDATE menu_items SET price=? WHERE id=?")->execute([max(0,(float)$_POST['price']),(int)$_POST['id']]);flash('Price updated.');}
 redirect('admin.php?page=menu');
}
$cats=db()->query("SELECT * FROM categories ORDER BY sort_order,name")->fetchAll();$items=db()->query("SELECT m.*,c.name category FROM menu_items m JOIN categories c ON c.id=m.category_id ORDER BY c.sort_order,m.sort_order,m.name")->fetchAll();
?><h1 class="h1">Menu Management</h1><p class="muted">Change prices, add items, and make items unavailable without changing QR codes.</p>
<div class="row"><div class="card"><h2>Add Category</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="cat"><label>Name</label><input name="name" required><label>Sort Order</label><input type="number" name="sort_order" value="1"><button class="btn gold" style="margin-top:10px">Add Category</button></form></div>
<div class="card"><h2>Add Menu Item</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="item"><div class="row"><div><label>Category</label><select name="category_id"><?php foreach($cats as $c): ?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div><label>Price (<?=e(currency_symbol())?>)</label><input type="number" step="0.01" name="price" required></div></div><label>Item Name</label><input name="name" required><label>Description</label><textarea name="description"></textarea><label>Sort Order</label><input type="number" name="sort_order" value="1"><label><input type="checkbox" name="available" checked style="width:auto"> Available</label><button class="btn gold" style="margin-top:10px">Add Item</button></form></div></div>
<div class="card"><table class="table"><tr><th>Item</th><th>Category</th><th>Price</th><th>Availability</th><th>Action</th></tr><?php foreach($items as $i): ?><tr><td><b><?=e($i['name'])?></b><div class="muted"><?=e($i['description'])?></div></td><td><?=e($i['category'])?></td><td><form method="post" style="display:flex;gap:5px"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="price"><input type="hidden" name="id" value="<?=$i['id']?>"><input name="price" value="<?=e((string)$i['price'])?>" style="max-width:100px"><button class="btn small">Save</button></form></td><td><span class="pill <?=$i['available']?'green':'red'?>"><?=$i['available']?'Available':'Unavailable'?></span></td><td><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$i['id']?>"><button class="btn small light"><?=$i['available']?'Disable':'Enable'?></button></form></td></tr><?php endforeach;?></table></div>