<?php
if(!is_admin() && !can('can_manage_tables')){echo '<div class="card">Tables & QR permission denied.</div>';return;}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$a=$_POST['action']??'';if($a==='add'){$n=trim($_POST['table_no']??'');if($n){$s=db()->prepare("INSERT INTO restaurant_tables(table_no,qr_token) VALUES(?,?)");$s->execute([$n,bin2hex(random_bytes(24))]);flash('Table added.');}}elseif($a==='toggle'){$s=db()->prepare("UPDATE restaurant_tables SET active=1-active WHERE id=?");$s->execute([(int)$_POST['id']]);flash('Table status updated.');}redirect('admin.php?page=tables');}
$tables=db()->query("SELECT * FROM restaurant_tables ORDER BY table_no+0,table_no")->fetchAll();
?><div style="display:flex;justify-content:space-between;align-items:center"><div><h1 class="h1">Tables & QR</h1><p class="muted">Add/remove/disable tables whenever you want.</p></div></div>
<div class="card"><form method="post" class="row"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="add"><div><label>Table Number / Name</label><input name="table_no" placeholder="e.g. 11" required></div><div style="display:flex;align-items:end"><button class="btn gold">+ ADD TABLE</button></div></form></div>
<div class="grid"><?php foreach($tables as $t): $url=APP_URL.'/index.html?table='.$t['qr_token']; ?><div class="card" style="text-align:center"><h2>TABLE <?=e($t['table_no'])?></h2><span class="pill <?=$t['active']?'green':'red'?>"><?=$t['active']?'Active':'Disabled'?></span><div class="qrbox" id="qr<?=$t['id']?>"></div><div class="actions" style="justify-content:center"><button class="btn small" onclick="shareQR('<?=e($url)?>','<?=e($t['table_no'])?>')">Share</button><button class="btn small light" onclick="printQR(<?=$t['id']?>)">Print</button><button class="btn small light" onclick="downloadQR(<?=$t['id']?>,'<?=e($t['table_no'])?>')">Download</button><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$t['id']?>"><button class="btn small danger"><?=$t['active']?'Disable':'Enable'?></button></form></div></div><?php endforeach;?></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script><script>
const rows=<?=json_encode(array_map(fn($t)=>['id'=>$t['id'],'url'=>APP_URL.'/index.html?table='.$t['qr_token']],$tables))?>;
rows.forEach(x=>new QRCode(document.getElementById('qr'+x.id),{text:x.url,width:150,height:150,colorDark:'#173b2b',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H}));
const restaurantName=<?=json_encode(restaurant_name())?>;function shareQR(url,no){if(navigator.share)navigator.share({title:restaurantName+' Table '+no,text:'Scan to order',url});else navigator.clipboard.writeText(url).then(()=>alert('QR link copied.'))}
function downloadQR(id,no){const c=document.querySelector('#qr'+id+' canvas');if(!c)return;const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='table-'+no+'-qr.png';a.click()}
function printQR(id){const c=document.querySelector('#qr'+id);const w=window.open('','_blank');w.document.write('<html><body style="text-align:center;font-family:Arial"><img src="<?=e(logo_url())?>" style="max-width:260px;max-height:140px;object-fit:contain"><h1><?=e(restaurant_name())?></h1><h2>'+c.parentElement.querySelector('h2').innerText+'</h2>'+c.outerHTML+'<p>Scan to Order</p></body></html>');setTimeout(()=>w.print(),500)}
</script>